sudo: required
service:
  - docker
before_install:
  - docker build -t  Parashuraam/docker-nodejs-demo  -f Dockerfile.dev .
script:
  - docker build -t  Parashuraam/docker-nodejs-demo npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    branch: manster
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
